### ISSUE TITLE
Crash on clicking proceed at campfire before boss

### ISSUE THREAD

**Issue by gaggle331** [WonkyMic/NavigateTheSpire#3]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at Map.MapUtil.getNextMapRoomNode(MapUtil.java:34) ~[NavigateTheSpire.jar:?]
	at AdviceMod.invokeNextMapNode(AdviceMod.java:50) ~[NavigateTheSpire.jar:?]
	at AdviceMod.receivePostUpdate(AdviceMod.java:68) ~[NavigateTheSpire.jar:?]
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2204) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:913) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:464) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by gaggle331** [comment]
Crash after killing boss:

java.lang.NullPointerException: null
	at Map.MapUtil.pickBestPath(MapUtil.java:99) ~[NavigateTheSpire.jar:?]
	at Map.MapUtil.createOptimalPath(MapUtil.java:65) ~[NavigateTheSpire.jar:?]
	at Map.MapUtil.getNextMapRoomNode(MapUtil.java:43) ~[NavigateTheSpire.jar:?]
	at AdviceMod.invokeNextMapNode(AdviceMod.java:50) ~[NavigateTheSpire.jar:?]
	at AdviceMod.receivePostUpdate(AdviceMod.java:68) ~[NavigateTheSpire.jar:?]
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2204) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:913) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:464) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
